version: '3.7'

services:
    wireguard:
        image: lscr.io/linuxserver/wireguard
        networks:
            - vpn-bridge
        volumes:
            - ../peer_mower_srv.conf:/config/wg0.conf
            - /lib/modules:/lib/modules
        environment:
            - PUID=1000
            - PGID=1000
        cap_add: 
            - NET_ADMIN
            - SYS_MODULE
        sysctls:
            - net.ipv4.conf.all.src_valid_mark=1

    ros:
        image: mower/ros
        build:
            context: ./ros
            dockerfile: Dockerfile
        network_mode: service:wireguard

networks:
    vpn-bridge:
        driver: bridge
