version: "2.1"
  
services:
    wireguard:
      image: lscr.io/linuxserver/wireguard:latest
      cap_add:
          - NET_ADMIN
          - SYS_MODULE
      environment:
          - PUID=1000
          - PGID=1000
          - TZ=Europe/London
          - SERVERURL=mower.awiki.org
          - SERVERPORT=51821 # this only appears to change the port in the written config, not the actual daemon, so remap it in docker ports
          - PEERS=conf,robot0,robot1
          - PEERDNS=1.1.1.1
          - INTERNAL_SUBNET=10.13.13.0
          - ALLOWEDIPS=0.0.0.0/0
          - LOG_CONFS=true
      volumes:
          - ../wireguard:/config
          - /lib/modules:/lib/modules
      ports:
          - 51821:51820/udp
      sysctls:
          - net.ipv4.conf.all.src_valid_mark=1
      restart: unless-stopped
