version: '3.7'

services:
    wireguard:
        image: lscr.io/linuxserver/wireguard
        networks:
            - vpn-bridge
        volumes:
            - ../peer_mower_srv.conf:/config/wg0.conf
            - /lib/modules:/lib/modules
        environment:
            - PUID=1000
            - PGID=1000
        cap_add: 
            - NET_ADMIN
            - SYS_MODULE
        sysctls:
            - net.ipv4.conf.all.src_valid_mark=1

    ros:
        image: mower/ros
        build:
            context: ./ros
            dockerfile: Dockerfile
        network_mode: service:wireguard
        volumes:
            - /home/mcomp/logs:/logs
        env_file:
            - db.env

    server-side:
        image: mower/serverside
        build:
            context: ./server-side
            dockerfile: Dockerfile
        ports:
            - 2005:2005
        env_file:
            - db.env

    nginx:
        image: nginx
        ports:
            - 2006:2006
        volumes:
            - ./nginx/nginx.conf:/etc/nginx/nginx.conf

    db:
        image: mariadb:10.10.2
        env_file:
            - db.env
        ports:
            - 3306:3306
        volumes:
            - database-vol:/var/lib/mysql

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        environment:
            - PMA_HOST=db
            - PMA_PORT=3306
            - PMA_ARBITRARY=1
        ports:
            - 8080:80
        links:
            - db

networks:
    vpn-bridge:
        driver: bridge

volumes:
    database-vol:
